# Generated by Django 2.2.5 on 2021-07-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
